pub mod after_process;
pub mod codegen;
pub mod environment;
mod expression_codegen;
mod expression_static;
mod function;
pub mod generator;
mod interpret_fn;
mod info_collector;
mod namer;
pub mod scope_information;
pub mod scope;
mod statement;
pub mod summarygen;
mod template;
mod type_check;
mod type_infer;
mod utils;
